# Generated by Django 5.0 on 2024-01-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('tourist', 'Tourist'), ('host', 'Host')], default='tourist', max_length=10),
        ),
    ]
