# Generated by Django 5.0 on 2023-12-28 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeType', models.CharField(max_length=50)),
                ('serviceName', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('operatingTime', models.JSONField()),
                ('description', models.JSONField()),
                ('introduction', models.TextField()),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='storage_images/')),
                ('contact_info', models.CharField(max_length=100)),
                ('hostUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='menu_images/')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='storages.storage')),
            ],
        ),
    ]
