# Generated by Django 5.0 on 2024-01-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='image',
            field=models.ImageField(blank=True, upload_to='storage_images/'),
        ),
    ]
